color_1:
  default: "var(--color-tertiary-very-low)"
  type: string
color_2:
  default: "var(--primary-very-low)"
  type: string
show_placeholder_img:
  default: true
  type: bool
  description: "If true, shows an image when there are no reminders. If unchecked, shows a message instead."
